// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2u7OxjdU1b8aifsl73ol07Hj3U9YzJkk',
    appId: '1:283205500530:web:b7c1be092f871a34668ceb',
    messagingSenderId: '283205500530',
    projectId: 'captura-97f07',
    authDomain: 'captura-97f07.firebaseapp.com',
    storageBucket: 'captura-97f07.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHtiwFZHDy32MGtjV1RYuG65NBzQaRdKc',
    appId: '1:283205500530:android:2c65cbdf232a76c8668ceb',
    messagingSenderId: '283205500530',
    projectId: 'captura-97f07',
    storageBucket: 'captura-97f07.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVEwm4mzdq_-Qr_qi3L1GIW_9vPDMJfCQ',
    appId: '1:283205500530:ios:e90960bb6cd7a52f668ceb',
    messagingSenderId: '283205500530',
    projectId: 'captura-97f07',
    storageBucket: 'captura-97f07.appspot.com',
    iosBundleId: 'com.example.captura',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVEwm4mzdq_-Qr_qi3L1GIW_9vPDMJfCQ',
    appId: '1:283205500530:ios:e90960bb6cd7a52f668ceb',
    messagingSenderId: '283205500530',
    projectId: 'captura-97f07',
    storageBucket: 'captura-97f07.appspot.com',
    iosBundleId: 'com.example.captura',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2u7OxjdU1b8aifsl73ol07Hj3U9YzJkk',
    appId: '1:283205500530:web:000ee258545aa07e668ceb',
    messagingSenderId: '283205500530',
    projectId: 'captura-97f07',
    authDomain: 'captura-97f07.firebaseapp.com',
    storageBucket: 'captura-97f07.appspot.com',
  );
}
